version: "3.8"

services:
  s_manager_agent_db:
    image: postgres:15
    container_name: s_manager_agent_db
    environment:
      POSTGRES_USER: ${AGENT_DB_USER}
      POSTGRES_PASSWORD: ${AGENT_DB_PASS}
      POSTGRES_DB: ${AGENT_DB_NAME}
    ports:
      - "${AGENT_DB_IP}:${AGENT_DB_PORT}:5432"
    volumes:
      - agent_db_data:/var/lib/postgresql/data
    networks:
      - SManagerTestNetwork

  s_manager_core_db:
    image: postgres:15
    container_name: s_manager_core_db
    environment:
      POSTGRES_USER: ${CORE_DB_USER}
      POSTGRES_PASSWORD: ${CORE_DB_PASS}
      POSTGRES_DB: ${CORE_DB_NAME}
    ports:
      - "${CORE_DB_IP}:${CORE_DB_PORT}:5432"
    volumes:
      - core_db_data:/var/lib/postgresql/data
    networks:
      - SManagerTestNetwork

volumes:
  agent_db_data:
  core_db_data:

networks:
  SManagerTestNetwork:
    driver: bridge
