ALTER TABLE users
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE users
SET created_at = COALESCE(created_at, last_update, CURRENT_TIMESTAMP)
WHERE created_at IS NULL;
